### ISSUE TITLE
When value is bound to model, change handler passed null.

### ISSUE THREAD

**Issue by tomchiverton** [tannerlinsley/nz-toggle#1]
It would also be nice if the change handler was passed the context and/or $event so if there are many controls it would know know which was clicked.

**Comment by tannerlinsley** [comment]
@tomchiverton I'll take a look at this.  I'll be diving in deep on ng-toggle for a refactor here soon, too.  If you're interested in contributing, let me know!

**Comment by tannerlinsley** [comment]
Change events can be monitored using ng-change or scope watches if needed. A new on-toggle function callback fires only when the toggle is changed via the button. This function passes the value of the toggle when possible.
