### ISSUE TITLE
Use NgModelController

### ISSUE THREAD

**Issue by kentcdodds** [tannerlinsley/nz-toggle#13]
I see that you're using `ngModel: '='`. Instead you should use `require` and utilize the existing `NgModelController`'s functions to set the value of the model. This will make it work better with validation and other directives like `ngChange`. For more info, see: https://docs.angularjs.org/api/ng/type/ngModel.NgModelController and https://docs.angularjs.org/guide/directive (search for `require:`)

**Comment by kentcdodds** [comment]
Note, you'll use `require: 'ngModel'` to get ahold of the `ngModelController` instance for this element, then you'll use [`$setViewValue`](https://docs.angularjs.org/api/ng/type/ngModel.NgModelController#$setViewValue) instead of `ngModel = 'foo'`

**Comment by tannerlinsley** [comment]
I'll try and get this implemented as soon as possible

**Comment by devvteam** [comment]
@kentcdodds  can you provide me an example? I need to validate a nz-toggle and I'm not able to succeed... Thanks in advance

**Comment by kentcdodds** [comment]
@devvteam, currently `nz-toggle` is still using `ngModel: '='`, so doing validation using the normal mechanisms isn't going to work. I'm sure @tannerlinsley would love a PR.

I, however, don't have a use case for nz-toggle anymore. So this can be closed as far as I'm concerned.
