### ISSUE TITLE
Disabled support?

### ISSUE THREAD

**Issue by StormRider01** [tannerlinsley/nz-toggle#21]
It would be great if we could set a disabled status.

**Comment by tannerlinsley** [comment]
Excellent idea.

**Comment by lehne** [comment]
Button shows disabled styling but does not disable. This would be nice

**Comment by nestdimon** [comment]
@lehne, are you sure? In [this exaple](http://codepen.io/anon/pen/BNMVRE) it works fine.

**Comment by ckr** [comment]
Works fine for us, when do you think we could get this in a tag?

**Comment by tannerlinsley** [comment]
I would be willing to add collaborator status and npm access to anyone who
wants to help maintain this project.

**Comment by ckr** [comment]
I would be willing to help.

**Comment by tannerlinsley** [comment]
@ckr I've added you as a collaborator.  Don't by shy to review PR's, triage bugs, or discuss updates/refactors/new functionality etc.

**Comment by ckr** [comment]
@tannerlinsley Thanks will do. :)
