### ISSUE TITLE
Distribution Files Log to Console

### ISSUE THREAD

**Issue by hawkerm** [tannerlinsley/nz-toggle#28]
The files in the dist directory shouldn't output to the console.  When including it as a library you don't want a ton of extra output in your browser.  It makes debugging your own application a lot harder.

**Comment by tannerlinsley** [comment]
I agree. I'll accept a PR

**Comment by lavor** [comment]
I have the same issue, when button is dragged the console log is owerwhelmed with info messages:

![nz-toggle-logging-of-dragging](https://cloud.githubusercontent.com/assets/7839054/15209176/f8d28642-182f-11e6-9467-77d93539c7dd.png)

**Comment by ckr** [comment]
Removed.

**Comment by lavor** [comment]
Hi, sorry I don't understand, how can be console logs removed, when you changed with your commit just readme file?

**Comment by ckr** [comment]
They where removed in a previous commit.

**Comment by lavor** [comment]
Problem is probably in "mismatch Version declared in the json (2.1.0) is different than the resolved one (2.2.0)":
`bower nz-toggle#*               cached https://github.com/tannerlinsley/nz-toggle.git#2.1.0
bower nz-toggle#*             validate 2.1.0 against https://github.com/tannerlinsley/nz-toggle.git#*
bower nz-toggle#*                  new version for https://github.com/tannerlinsley/nz-toggle.git#*
bower nz-toggle#*              resolve https://github.com/tannerlinsley/nz-toggle.git#*
bower nz-toggle#*             checkout 2.2.0
bower nz-toggle#*             mismatch Version declared in the json (2.1.0) is different than the resolved one (2.2.0)
bower nz-toggle#*             resolved https://github.com/tannerlinsley/nz-toggle.git#2.2.0
bower nz-toggle#~2.2.0         install nz-toggle#2.2.0`

**Comment by ckr** [comment]
Sorry forgot to update the version in the bower and npm files.

**Comment by lavor** [comment]
Now, it is OK, thanks.
