### ISSUE TITLE
Support dynamic tooltip texts

### ISSUE THREAD

**Issue by moravcik** [tannerlinsley/nz-toggle#31]
Tooltip values `tip-true`, `tip-false`, `tip-null` are de-facto one time bound with once calling `$eval` on them. I would need them to be localized with angular-translate, but it doesn't work with asynchronous loading of translations (partial loader), because at time of calling `$eval` on tip-texts the translation is not yet available (it is available few milliseconds later) but it is not evaluated later.

**Comment by ckr** [comment]
Reopen if not done.
