### ISSUE TITLE
Circular nz-toggle

### ISSUE THREAD

**Issue by ptitdje45** [tannerlinsley/nz-toggle#39]
![image](https://cloud.githubusercontent.com/assets/23073597/22687328/d048ce52-ed27-11e6-8da2-d35d4f69a2ab.png)

For the moment i just changed in html : 
element.style {
    width: 45px;
    height: 45px;
    background-color: rgb(255, 204, 153);
}
.nz-toggle {
    display: block;
    width: 200%;
    height: 100%;
    margin-left: -19px;
    position: relative;
    cursor: pointer;
}

So that's what i would like to do, but i don't really know how to change source to get that only in a part of my application.

Thanks in advance,

Jérémy

**Comment by ckr** [comment]
Hi,

When you call nz-toggle within your angular app you can give it any css class you want.

For example.

`<nz-toggle tri-toggle ng-model="myValue7" class="round"></nz-toggle>`

**Comment by ptitdje45** [comment]
Yeah i did my own nz-toggle ;)

**Comment by ckr** [comment]
Ok, so shall i close this then?

**Comment by ptitdje45** [comment]
Yes you can :)
