### ISSUE TITLE
Improve Accessibility

### ISSUE THREAD

**Issue by kentcdodds** [tannerlinsley/nz-toggle#7]
This is pretty much not accessible at all. If you include `ngAria`, then you can tab to the UI component, but it doesn't give any indication to the user that it has focus. Things to do:
- Add styles for `:focus` on `ng-toggle-switch`
- Add `tabindex="0"` on `ng-toggle-switch`
- Add `tabindex="-1"` on the `ng-model` element (`ng-toggle-wrap`). (to prevent `ngAria` from adding a `tabindex`)

Bonus stuff:
- Add `role="checkbox"` if it's not a `triToggle` and add the appropriate aria attributes: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_checkbox_role
- Add `role="button"` if it is a `triToggle` and add the appropriate aria attributes: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role

**Comment by kentcdodds** [comment]
Oh, one other thing. Make it so I can move my arrows left and right to toggle or up and down when it's vertical.

**Comment by tannerlinsley** [comment]
Okay

**Comment by marcysutton** [comment]
It should also be operable with the space bar or enter key. Regular switch toggles are just like ARIA checkboxes. Here are some tips for tri-state toggles: https://webaccessibility.withgoogle.com/unit?unit=6&lesson=14

**Comment by kentcdodds** [comment]
Thanks @marcysutton!

**Comment by tannerlinsley** [comment]
Excellent resource!

**Comment by tannerlinsley** [comment]
ng-toggle is going to get some great attention here pretty quick.  The
feature I'm using it in just reentered our product, so I might be doing
some breaking changes in a 2.0 along with all of the issues.

**Comment by kentcdodds** [comment]
Woot!

**Comment by tannerlinsley** [comment]
I'm hoping 2.0 can live up to expectations. I'd like to see it used on a larger scale.

**Comment by tannerlinsley** [comment]
😂
