### ISSUE TITLE
Fix example that integrates with angular-formly

### ISSUE THREAD

**Issue by kentcdodds** [tannerlinsley/nz-toggle#8]
Here's a start: https://jsbin.com/qatiku/edit?html,js,output

There are a few funny stylistic things wrong with it.

**Comment by tannerlinsley** [comment]
That's awesome!

**Comment by kentcdodds** [comment]
Version 2.0 doesn't support border-radius anymore.

**Comment by tannerlinsley** [comment]
As an attribute setting, no.  Adding the class "square" to
<nz-toggle></nz-toggle> will switch to a 2px border radius, and you can
always style via the classes.  It doesn't offer as much fine grain and on
demand control as before, but the logic for the radii was extremely
horrible, bulky and annoying from the beginning.  We could bring it back in
a future version with some better logic, but for the meantime, it was
better to not be in this release I think.

**Comment by kentcdodds** [comment]
Cool, I'm good with that. Just checking.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by tannerlinsley** [comment]
@kentcdodds Using the latest release, are some of the visual errors fixed now?

**Comment by kentcdodds** [comment]
Sorry buddy... We actually had to pull it out because someone didn't like the toggle experience (wanted to use a checkbox instead) :-( I'll let you know if I use it again.

**Comment by kentcdodds** [comment]
Feel free to make the example awesome and add it to the angualr-formly-website :-)

**Comment by tannerlinsley** [comment]
No worries.  Closing for now :)
